name = "tiny"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "tiny"

# Build configuration
[build]
command = "npm run build"

routes = [
  { pattern = "tiny.ganeshagrawal.com", custom_domain = true }
]